apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.zookeeper.init.name }}
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: {{ .Values.zookeeper.init.backofflimit }}
  template:
    spec:
      containers:
      - name: {{ .Values.zookeeper.init.name }}
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
        command:
          - /bin/bash
          - -o
          - pipefail
          - -euc
          - >
            server={{- include "siembol.zookeeper.server" . | quote -}};
            zkCli.sh -server ${server} get /siembol >/dev/null -w || zkCli.sh -server ${server} create /siembol >/dev/null;
            {{- range .Values.zookeeper.init.nodes}}
                {{- with . }}
                  zkCli.sh -server ${server} get {{ .name }} >/dev/null || zkCli.sh -server ${server} create {{ .name }} >/dev/null;
                  zkCli.sh -server ${server} set {{ .name }} '{}' >/dev/null;
                {{- end}}
            {{- end}}
      restartPolicy: Never
