{
 "title": "Siembol",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Siembol Total Kafka Lag",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag)"
    }
   ]
  },
  {
   "title": "Siembol Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "kafka_consumergroup_group_lag", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Alerts - Total alerting rule matches since last topology restart",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "siembol_alerts_siembol_counter_alerting_rule{alerting_rule_type=\"matches\"}",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Alerting Rule: matches per rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "siembol_alerts_siembol_counter_alerting_rule{alerting_rule_type=\"matches\"}",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Alerts - Total alerting rule protection matches since last topology restart",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "siembol_alerts_siembol_counter_alerting_rule{alerting_rule_type=\"protection\"}",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Alerting Rule: Protection matches per rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "siembol_alerts_siembol_counter_alerting_rule{alerting_rule_type=\"protection\"}",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Parsing apps: Total parsed messages since last topology restart",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "parsing_app_siembol_counter_app_messages{message_type=\"parsed\"}",
     "legendFormat": "{{application_type}}"
    }
   ]
  },
  {
   "title": "Parsing apps - Parsed messages - rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(parsing_app_siembol_counter_app_messages{message_type=\"parsed\"}[1m])",
     "legendFormat": "{{application_type}}"
    }
   ]
  },
  {
   "title": "Parsing apps: Total error messages since last topology restart",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "parsing_app_siembol_counter_app_messages{message_type=\"error\"}",
     "legendFormat": "{{application_type}}"
    }
   ]
  },
  {
   "title": "Parsing apps - Error messages - rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(parsing_app_siembol_counter_app_messages{message_type=\"error\"}[1m]))",
     "legendFormat": "{{application_type}}"
    }
   ]
  },
  {
   "title": "Parsing apps: Parsed messages per source type: rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(parsing_app_sourcetype_siembol_counter_messages{message_type=\"parsed\"}[1m]))",
     "legendFormat": "{{source_type}}"
    }
   ]
  },
  {
   "title": "Heartbeat - Total Siembol latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "siembol_gauge_heartbeat_latency_ms_total",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Heartbeat -  Responding SIembol latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "siembol_gauge_heartbeat_latency_ms_responding",
     "legendFormat": "responding"
    }
   ]
  },
  {
   "title": "Heartbeat - Enriching Siembol latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "siembol_gauge_heartbeat_latency_ms_enriching",
     "legendFormat": "enriching"
    }
   ]
  },
  {
   "title": "Heartbeat - Parsing Siembol latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "siembol_gauge_heartbeat_latency_ms_parsing",
     "legendFormat": "parsing"
    }
   ]
  }
 ]
}