{{- if (has "enrichment_store" .Values.enabled_apps) -}}
{{- if .Values.enrichment_store.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "siembol.enrichment_store.fullname" $ }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT"
    {{- if .Values.certmanager.enabled }}
    cert-manager.io/issuer: ca-issuer
    {{- end }}
    {{- if .Values.enrichment_store.oauth2_proxy.enabled }}
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.enrichment_store.oauth2_proxy.host }}/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Values.enrichment_store.oauth2_proxy.host }}/oauth2/auth
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
    {{- end }}
spec:
  {{ if .Values.tls.enabled -}}
  tls:
  - hosts: 
    - {{ .Values.enrichment_store.ingress.fqdn }}
    secretName: {{ include "siembol.enrichment_store.fullname" $ }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.enrichment_store.ingress.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "siembol.enrichment_store.fullname" $ }}
            port: 
              number: {{ .Values.enrichment_store.service.port }}
{{- end -}}
{{- end -}}
