{{- if .Values.ui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "siembol.manager.appname.fullname" $ }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/issuer: ca-issuer
spec:
  {{ if .Values.tls.enabled -}}
  tls:
  - hosts: 
    - {{ .Values.manager.ingress.hostname }}
    secretName: {{ include "siembol.manager.appname.fullname" $ }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.manager.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "siembol.manager.appname.fullname" $ }}
            port: 
              number: 8082
{{- end -}}