{{- if (has "manager" .Values.enabled_apps) -}}
{{- if .Values.manager.serviceAccountEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccountName }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "siembol.manager.appname.fullname" $ }}-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "siembol.manager.appname.fullname" $ }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccountName }}
{{- end -}}
{{- end -}}
