apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-datasources
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server:8080
        access: proxy
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.configmapName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
data:
  siembol_dashboard.json: |-
{{ .Files.Get .Values.grafana.prometheusDashboardName | indent 4 }}
---