{{- if (has "response" .Values.enabled_apps) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "siembol.response.fullname" $ }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "siembol.response.fullname" $ }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "siembol.response.fullname" $ }}
      name: {{ include "siembol.response.fullname" $ }}
    spec:
      containers:
      - image: {{ .Values.response.image.name }}:{{ .Values.response.image.tag }}
        imagePullPolicy: {{ .Values.response.image.pullPolicy }}
        name: {{ include "siembol.response.fullname" $ }}
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.5"
          limits:
            memory: "256Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: {{ .Values.response.health.path }}
            port: {{ .Values.response.health.port }}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: {{ .Values.response.health.path }}
            port: {{ .Values.response.health.port }}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: JAVA_OPTS
          value: {{ .Values.response.javaOpts }}
        volumeMounts:
        - name: cacerts
          mountPath: /etc/ssl/certs/java/cacerts
          subPath: cacerts
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: cacerts
        secret:
          secretName: cacerts
{{- end -}}