{{- if (has "enrichment_store" .Values.enabled_apps) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.enrichment_store.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.enrichment_store.pvc.storageclass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.enrichment_store.pvc.storage }}
{{- end -}}