apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "siembol.rest.fullname" $ }}
  namespace: {{ .Values.namespace }}
data:
  application.properties: |-
{{ .Files.Get .Values.rest.applicationProperties | indent 4 }}
