{{- if (has "rest" .Values.enabled_apps) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "siembol.rest.fullname" $ }}
  name: {{ include "siembol.rest.fullname" $ }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ include "siembol.rest.fullname" $ }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "siembol.rest.fullname" $ }}
      name: {{ include "siembol.rest.fullname" $ }}
    spec:
      containers:
      - image: {{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag }}
        workingDir: {{ .Values.rest.mountPath }}
        imagePullPolicy: {{ .Values.rest.image.PullPolicy }}
        name: {{ include "siembol.rest.fullname" $ }}
        ports:
          - containerPort: {{ .Values.rest.containerPort }}
        resources:
          requests:
            memory: {{ .Values.rest.resources.requests.memory }}
            cpu: {{ .Values.rest.resources.requests.cpu }}
          limits:
            memory: {{ .Values.rest.resources.limits.memory }}
            cpu: {{ .Values.rest.resources.limits.cpu }}
        securityContext:
          runAsUser: 101
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.rest.containerPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.rest.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.rest.readinessProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.rest.containerPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.rest.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.rest.livenessProbe.periodSeconds }}
        {{ if .Values.rest.configmap.enabled -}}
        envFrom:
        - configMapRef:
            name: {{ .Values.rest.configmap.name }}
        {{ end }}
        env:
        - name: XDG_CONFIG_HOME
          value: /config/jgit/.config
        - name: JAVA_OPTS
          value: {{ .Values.rest.javaOpts }}
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "siembol.rest.fullname" $ }}-secrets
              key: git
        volumeMounts:
        - name: cacerts
          mountPath: /etc/ssl/certs/java/cacerts
          subPath: cacerts
          readOnly: true        
        - name: rules-dir
          mountPath: {{ .Values.rest.rulesDir }}
        - name: config-dir
          mountPath: /config
      restartPolicy: Always
      volumes:
      - name: cacerts
        secret:
          secretName: cacerts
      - name: rules-dir
        emptyDir: {}
      - name: config-dir
        emptyDir: {}
      terminationGracePeriodSeconds: 300
{{- end -}}
