# -----------------------------------------------------------------------------
# oauth2 proxy parameters
# -----------------------------------------------------------------------------

extraEnvVars:
  - name: OAUTH2_PROXY_REDIRECT_URL
    value: https://oauth-proxy.siembol.local/oauth2/callback
  - name: OAUTH2_PROXY_CLIENT_ID
    value: "my client ID FROM ENV"
  - name: OAUTH2_PROXY_CLIENT_SECRET
    value: "my client SECRET ENV"
  - name: OAUTH2_PROXY_COOKIE_SECRET
    value: "Q1JFQVRFIFlPVVIgT1dOIFNFQ1JFVAo=" # your secret
  - name: OAUTH2_PROXY_COOKIE_DOMAIN
    value: .siembol.local 
  - name: OAUTH2_PROXY_COOKIE_EXPIRE
    value: 8h
  - name: OAUTH2_PROXY_COOKIE_NAME
    value: _siembol-oauth-proxy
ingress:
  enabled: true
  hosts:
    - oauth-proxy.siembol.local
  tls:
  - secretName: oauth2-proxy-tls
    hosts:
      - oauth-proxy.siembol.local
redis:
  enabled: false