# -----------------------------------------------------------------------------
# General seimbol parameters
# -----------------------------------------------------------------------------

namespace: "siembol"
environment: "dev"

# -----------------------------------------------------------------------------
# Default list of apps to deploy
# -----------------------------------------------------------------------------
enabled_apps: 
- ui
- rest
- manager
- dep_ingresses
- enrichment_store
- siembol_monitoring
- response
- demo_kafka_producer

# Enable certmanager 
certmanager:
  enabled: true

# Enable TLS via certmanager
tls:
  enabled: true

# -----------------------------------------------------------------------------
# Ingress for dependencies parameters
# -----------------------------------------------------------------------------
dep_ingresses:
  enrichment_store:
    enabled: true
    fqdn: enrichment.siembol.local
    oauth2_proxy:
      enabled: false
      host: oauth-proxy.siembol.local
  storm:
    enabled: true
    name: storm
    fqdn: storm.siembol.local
    service:
      name: storm-ui
      port: 8080
    oauth2_proxy:
      enabled: false
      host: oauth-proxy.siembol.local

# -----------------------------------------------------------------------------
# enrichment store parameters
# -----------------------------------------------------------------------------

enrichment_store:
  appName: "enrichment-store"
  image:
    repository: php
    tag: 8.1-apache
    pullPolicy: Always
  securityContext:
    runAsUser: 82
  containerPort: 80
  service:
    port: 80
  pvc:
    name: "files-store"
    storageclass: ""
    storage: 1Gi

  security:
    user: 82
    fsGroup: 82
    runAsGroup: 82

  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "256Mi"


# -----------------------------------------------------------------------------
# config-editor-rest parameters
# -----------------------------------------------------------------------------

rest:
  image: 
    repository: "gresearchdev/siembol-config-editor-rest"
    tag: "latest"
    pullPolicy: Always

  appName: "config-editor-rest"
  containerPort: 8081
  
  mountPath: "/opt/config-editor-rest"
  rulesDir: "/tmp/siembol-config"

  configmap:
    enabled: true
    name: "github-details"

  service:
    port: 8081
  ingress:
    enabled: true
    fqdn: rest.siembol.local
  
  javaOpts: "-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts"

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  readinessProbe:
    initialDelaySeconds: 150
    periodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 150
    periodSeconds: 10

# -----------------------------------------------------------------------------
# config-editor-ui parameters
# -----------------------------------------------------------------------------

ui:
  image: 
    repository: "gresearchdev/siembol-config-editor-ui"
    tag: "latest"
    pullPolicy: Always

  appName: "config-editor-ui"
  containerPort: 8080

  service:
    port: 8080
    intport: 80

  # Run with an ingress
  ingress:
    enabled: true
    fqdn: ui.siembol.local

  resources:
    requests:
      cpu: 0.1
      memory: "128Mi"
    limits:
      cpu: 0.5
      memory: "256Mi"

  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30


# -----------------------------------------------------------------------------
# storm-topology-manager parameters
# -----------------------------------------------------------------------------

manager:
  appName: "storm-topology-manager"
  serviceAccountName: "storm-topology-controller"
  serviceAccountEnabled: true
  image: 
    repository: "gresearchdev/siembol-storm-topology-manager"
    tag: "latest"
    pullPolicy: Always
  containerPort: 8082

  mountPath: "/opt/storm-topology-manager"
  javaOpts: "-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts"

  service:
    port: 8082

  # Run with an ingress
  ingress:
    enabled: true
    fqdn: topology-manager.siembol.local

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10

  resources:
    requests:
      cpu: "400m"
      memory: "128Mi"
    limits:
      cpu: "800m"
      memory: "512Mi"


# -----------------------------------------------------------------------------
# siembol response parameters
# -----------------------------------------------------------------------------
response:
  appName: "response"
  image:
    name: "gresearchdev/siembol-responding-stream"
    tag: "latest"
    pullPolicy: Always

  ingress:
    enabled: true
    fqdn: response.siembol.local

  service:
    port: 8080

  health:
    path: /health
    port: 8080

  javaOpts: "-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts"

  resources:
    requests:
      cpu: 0.5
      memory: "256Mi"
    limits:
      cpu: 1
      memory: "1024Mi"

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 10

# -----------------------------------------------------------------------------
# siembol monitoring parameters
# -----------------------------------------------------------------------------
siembol_monitoring:
  appName: "siembol-monitoring"
  image:
    repository: "gresearchdev/siembol-siembol-monitoring"
    tag: "latest"
    pullPolicy: Always

  service:
    port: 8083

  resources:
    requests:
      cpu: 0.1
      memory: "128Mi"
    limits:
      cpu: 0.5
      memory: "256Mi"

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30

# -----------------------------------------------------------------------------
# demo kafka producer
# -----------------------------------------------------------------------------
demo_kafka_producer:
  appName: "demo-kafka-producer"
  appPath: "/opt/app"
  image:
    repository: "python"
    tag: "3.10-slim-bullseye"
    pullPolicy: Always

  jobs:
    cloudtrail:
      KAFKA_TOPIC: "aws.cloudtrail"
      MESSAGE_FREQUENCY_PER_SECOND: 10
      MESSAGE_KEY: "cloudtrail"
      KAFKA_SERVERS: "kafka-0.kafka-headless.siembol.svc.cluster.local:9092"
      PYTHONUNBUFFERED: 1
    eventlogs:
      KAFKA_TOPIC: "win.eventlogs"
      MESSAGE_FREQUENCY_PER_SECOND: 20
      MESSAGE_KEY: "eventlogs"
      KAFKA_SERVERS: "kafka-0.kafka-headless.siembol.svc.cluster.local:9092"
      PYTHONUNBUFFERED: 1
   
  resources:
    requests:
      cpu: 0.1
      memory: "128Mi"
    limits:
      cpu: 0.3
      memory: "256Mi"