FROM storm:2.2.0

ARG JAR
ARG CLASS
ENV TOPOLOGY_JAR=$JAR
ENV TOPOLOGY_CLASS=$CLASS
ARG USER="siembol"

RUN mkdir /$USER
RUN adduser --uid 101 --system --no-create-home --disabled-password --home /$USER --shell /sbin/nologin --group $USER

USER $USER

WORKDIR /$USER/deploy
COPY $TOPOLOGY_JAR .
COPY storm-entrypoint.sh /docker-entrypoint.sh
