FROM openjdk:8-jre-slim

RUN adduser --uid 101 --system --no-create-home --disabled-password --home /opt/config-editor-rest --shell /sbin/nologin --group config-editor-rest

EXPOSE 8080

ARG VERSION
ENV VERSION=$VERSION

WORKDIR /opt/config-editor-rest
COPY config-editor-rest /opt/config-editor-rest

USER config-editor-rest

CMD exec java $JAVA_OPTS -jar config-editor-rest-$VERSION.jar
