FROM storm:2.2.0

ARG JAR
ARG CLASS
ENV TOPOLOGY_JAR=$JAR
ENV TOPOLOGY_CLASS=$CLASS
ARG APP="siembol"

RUN adduser --uid 101 --system --no-create-home --disabled-password --home /$APP --shell /sbin/nologin --group $APP

USER $APP

WORKDIR /deploy
COPY $TOPOLOGY_JAR .
COPY storm-entrypoint.sh /docker-entrypoint.sh
