apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
      server {
        listen        80;
        server_name   localhost;

        location / {
            root html;
            index index.html;
        }
      }
    }
