apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;


        #autoindex on;               # enable directory listing output
        #autoindex_exact_size off;   # output file sizes rounded to kilobytes, megabytes, and gigabytes
        #autoindex_localtime on;     # output local times in the directory

        root   /usr/share/nginx/html;
        index  index.html index.htm;

        location / {
          try_files $uri/ =404;
        }
        location /uploads {
          limit_except POST              { deny all; } 

          client_body_temp_path          /etc/data;
          client_body_in_file_only       on;
          client_body_buffer_size        128K;
          client_max_body_size           20G;
          #echo_read_request_body; #t
          #echo $request_body_file;
          return 201 $request_body_file;
                #upload_pass: /data/upload;
                #alias /data/upload;
          #sendfile           on;
          proxy_pass  http://localhost:8080/;
          #dav_methods PUT ;
          #try_files $uri $uri/ =404;
          #root   /data;
          #index  index.html index.htm;

        }

        # location /data {
        #   root /;
        #   limit_except GET POST PUT { deny all; }
        #   client_max_body_size 50m; # 50 MB limit on file uploads
        #   client_body_buffer_size 128k;
        #   proxy_set_body $request_body_file;
        #   proxy_pass https://localhost:8080/data;
        #   proxy_redirect off;

        # }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

