apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen        8080;
      server_name   localhost;

      location / {
          root html;
          index index.html;
      }
    }

