{{- if (has "ui" .Values.enabled_apps) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "siembol.ui.fullname" $ }}
  name: {{ include "siembol.ui.fullname" $ }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "siembol.ui.fullname" $ }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "siembol.ui.fullname" $ }}
      name: {{ include "siembol.ui.fullname" $ }}
    spec:
      containers:
      - image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        name: {{ include "siembol.ui.fullname" $ }}
        securityContext:
          runAsUser: 101
        ports:
        - containerPort: {{ .Values.ui.containerPort }}
        readinessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.ui.service.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.ui.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ui.readinessProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.ui.service.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.ui.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ui.livenessProbe.periodSeconds }}
        resources:
         limits:
           cpu: {{ .Values.ui.resources.limits.cpu }}
           memory: {{ .Values.ui.resources.limits.memory }}
         requests:
           cpu: {{ .Values.ui.resources.requests.cpu }}
           memory: {{ .Values.ui.resources.requests.memory }}
      restartPolicy: Always
{{- end -}}