name: Unit Test Results

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      # we are not using actions/download-artifact here as
      # it does not yet support downloading from a different workflow
      # https://github.com/actions/download-artifact/issues/3
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: "unit-test-results|Event File"
          name_is_regexp: true
          path: artifacts

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: unit-test-results
          comment_title: Unit Test Results
          files: "artifacts/**/target/surefire-reports/TEST-*.xml"
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
