name: Unit Test Results

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      # we are not using actions/download-artifact here as
      # it does not yet support downloading from a different workflow
      # https://github.com/actions/download-artifact/issues/3
      - name: Download Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts && cd artifacts

          artifacts_url=${{ github.event.workflow_run.artifacts_url }}

          gh api --paginate $artifacts_url -q '.artifacts[] | select(.name=="unit-test-results" or .name=="Event File") | [.name, .archive_download_url] | @tsv' | while read artifact
          do
            IFS=$'\t' read name url <<< "$artifact"
            gh api $url > "$name.zip"
            unzip -d "$name" "$name.zip"
          done

          if [ $(ls . | wc -l) -eq 0 ]
          then
            echo "::error::No artifact with name 'unit-test-results' or 'Event File' exists"
            exit 1
          fi
        shell: bash

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: unit-test-results
          comment_title: Unit Test Results
          files: "artifacts/**/target/surefire-reports/TEST-*.xml"
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
