package uk.co.gresearch.siembol.alerts.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.github.reinert.jjschema.Attributes;
/**
 * A data transfer object for representing a rule protection specification used in alerting rules
 *
 * <p>This class is used for json (de)serialisation of a rule protection specification and
 * for generating json schema from this class using annotations.
 *
 * @author  Marian Novotny
 * @see com.github.reinert.jjschema.Attributes
 * @see com.fasterxml.jackson.annotation.JsonProperty
 * @see RuleDto
 * @see CorrelationRuleDto
 */
@Attributes(title = "rule protection", description = "Thresholds for deactivating the rule")
public class RuleProtectionDto {
    @JsonProperty("max_per_hour")
    @Attributes(required = true, description = "Maximum alerts generated by the rule per hour")
    Integer maxPerHour = 30;
    @JsonProperty("max_per_day")
    @Attributes(required = true, description = "Maximum alerts generated by the rule per hour")
    Integer maxPerDay = 100;

    public Integer getMaxPerHour() {
        return maxPerHour;
    }

    public void setMaxPerHour(Integer maxPerHour) {
        this.maxPerHour = maxPerHour;
    }

    public Integer getMaxPerDay() {
        return maxPerDay;
    }

    public void setMaxPerDay(Integer maxPerDay) {
        this.maxPerDay = maxPerDay;
    }
}
